### ISSUE TITLE
PHP 7 compatibility error

### ISSUE THREAD

**Issue by eugenealegiojo** [leafo/lessphp#624]
Method `lessc->string` caused error if you are running PHP 7.  It seems like 'string' is a reserved keyword introduced in PHP version 7.0.

Is someone also experiencing the same issue?

Cheers!

**Comment by tzkmx** [comment]
Yes, and also is the name of another variable, the errors are in these lines:
FOUND 5 ERRORS AFFECTING 5 LINES
------------------------------------------------------------------------------------------------------------------------------------
 2644 | ERROR | 'string' is a reserved keyword introduced in PHP version 7.0 and cannot be invoked as a function (T_STRING)
 2658 | ERROR | 'string' is a reserved keyword introduced in PHP version 7.0 and cannot be invoked as a function (T_STRING)
 2789 | ERROR | 'string' is a reserved keyword introduced in PHP version 7.0 and cannot be invoked as a function (T_STRING)
 2820 | ERROR | Function name, class name, namespace name or constant name can not be reserved keyword 'string' (since version 7.0)
 3074 | ERROR | 'string' is a reserved keyword introduced in PHP version 7.0 and cannot be invoked as a function (T_STRING)
--------------------

**Comment by Krinkle** [comment]
Appears to be fixed in latest master. Please report a new issue if you still experience difficulties with lessphp on PHP 7.
